const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();
 const base=process.env.REGISTRY_URL||'http://127.0.0.1:8769';
 await page.goto(base);await page.waitForSelector('.copy-button');
 assert.equal(await page.locator('.copy-button').count(),1+await page.locator('[data-package]').count());
 await page.locator('.command-block .copy-button').click();
 assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'kennel add changebucket');
 assert.match(await page.locator('.sr-only').textContent(),/Copied/);
 await page.getByRole('button',{name:'Copy install command for ability',exact:true}).click();
 assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'kennel add ability');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.locator('#main-nav').isVisible(),false);
 await page.getByRole('button',{name:'Open menu',exact:true}).click();
 assert.equal(await page.locator('#main-nav').isVisible(),true);
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#main-nav').isVisible(),false);
 assert.equal(await page.locator('.mobile-menu').evaluate(e=>document.activeElement===e),true);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'/tmp/kennel-mobile-icons.png'});
 await page.goto(base+'/mcp/1.1.1/');await page.waitForSelector('.copy-button');
 assert.equal(await page.locator('.copy-button').count(),2);
 await page.locator('pre').locator('..').locator('button').click();
 assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),await page.locator('pre').textContent());
 await page.locator('.command-block button').click();
 assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'kennel add mcp@1.1.1');
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error('denied')}}}));
 await page.locator('.command-block button').click();
 assert.match(await page.locator('.sr-only').textContent(),/unavailable/);
 await page.setViewportSize({width:1280,height:900});
 assert.equal(await page.locator('#main-nav').isVisible(),true);
 assert.equal(await page.locator('.mobile-menu').isVisible(),false);
 await page.screenshot({path:'/tmp/kennel-desktop-icons.png'});
 const plain=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});
 await plain.goto(base);assert.equal(await plain.locator('#main-nav').isVisible(),true);
 console.log('PASS: homepage copy controls; exact clipboard contents; dependency JSON; denied clipboard feedback; mobile toggle/Escape/focus; desktop navigation; no horizontal overflow; no-JS navigation');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
