name: Build official Kennel release package
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  package:
    uses: kujolang/kennel/.github/workflows/build-kennel-release.yml@226515d7a570cfaf8127dfae973953182f3a9280
