name: Build official Kennel release package
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  package:
    uses: kujolang/kennel/.github/workflows/build-kennel-release.yml@4fbe6481f6740abc9b239d617d0f366921978b3b
